#!/bin/bash

docker build . -t vpntest

exec docker run \
    --rm \
    --tty \
    --interactive \
    --device=/dev/net/tun \
    --cap-add=NET_ADMIN \
    --publish 127.0.0.1:1081:1080 \
    --volume "$(realpath "$1"):/ovpn.conf:ro" \
    --name vpntest \
    vpntest:latest
